spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/rWebApp
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/rWebApp
    user: postgres
    password: postgres
    baseline-on-migrate: true
    baseline-version: 1